export const NEW_QUESTION = 'NEW_QUESITON';
export const SHOW_ANSWERS = 'SHOW_ANSWERS';

export const SESSION_ACTION_TYPES = {
  LOGIN_REQUEST_STATE: 'LOGIN_STATE',
  LOGIN_STATUS_CHANGE: 'LOGIN_STATUS_CHANGE'
};
