export const NEW_QUESTION = 'NEW_QUESTION';
export const SHOW_ANSWERS = 'SHOW_ANSWERS';
export const SHOW_ANSWER_SUBMISSION = 'SHOW_ANSWER_SUBMISSION';
export const SHOW_SCORES = 'SHOW_SCORES';
export const LOGIN_REQUEST_STATE = 'LOGIN_STATE';
export const LOGIN_STATUS_CHANGE = 'LOGIN_STATUS_CHANGE';


export const CONNECT_TEAM = 'CONNECT_TEAM';
export const TEAM_ALLOWED = 'TEAM_ALLOWED';
export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const CONNECT_SCOREBOARD = 'CONNECT_SCOREBOARD';
export const ANSWER_SUBMITTED = 'ANSWER_SUBMITTED';
export const SHOW_QUESTION_RESULTS = 'SHOW_QUESTION_RESULTS';
export const END_OF_ROUND = 'END_OF_ROUND';


export default {
  NEW_QUESTION,
  SHOW_ANSWERS,
  SHOW_ANSWER_SUBMISSION,
  SHOW_SCORES,
  LOGIN_REQUEST_STATE,
  LOGIN_STATUS_CHANGE,
  CONNECT_TEAM,
  TEAM_ALLOWED,
  SUBMIT_ANSWER,
  CONNECT_SCOREBOARD,
  ANSWER_SUBMITTED,
  SHOW_QUESTION_RESULTS,
  END_OF_ROUND
};
