export const QUESTION_ACTION_TYPES = {
  FETCH_QUESTIONS: 'FETCH_QUESTIONS'
};

export const CATEGORY_ACTION_TYPES = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES'
};

export const QUIZNIGHT_ACTION_TYPES = {
  ACCEPT_TEAM: 'ACCEPT_TEAM',
  DECLINE_TEAM: 'DECLINE_TEAM',
  SET_QUIZNIGHT: 'SET_QUIZNIGHT'
};

export const GAME_ACTION_TYPES = {
  SET_GAME_STATE: 'SET_GAME_STATE',
  SET_GAME_START_REQUEST_STATE: 'SET_GAME_START_REQUEST_STATE'
};