export const QUESTION_ACTION_TYPES = {
  FETCH_QUESTIONS: 'FETCH_QUESTIONS'
};

export const CATEGORY_ACTION_TYPES = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES'
};

export const QUIZNIGHT_ACTION_TYPES = {
  ACCEPT_TEAM: 'ACCEPT_TEAM',
  DECLINE_TEAM: 'DECLINE_TEAM',
  SET_QUIZNIGHT: 'SET_QUIZNIGHT',
  NEW_TEAM: 'NEW_TEAM',
  ROUND_QUESTION_RECEIVED: 'ROUND_QUESTION_RECEIVED',
  ANSWER_RECEIVED: 'ANSWER_RECEIVED',
  ANSWER_RESUBMITTED: 'ANSWER_RESUBMITTED',
  SET_AMOUNT_QUESTIONS_PER_ROUND: 'SET_AMOUNT_QUESTIONS_PER_ROUND',
  EMPTY_CURRENT_QUESTION: 'EMPTY',
  EMPTY_STATE: 'EMPTY_STATE',
  SET_ROUND_NR: 'SET_ROUND_NR'
};

export const WEBSOCKET_ACTION_TYPES = {
  CONNECT_QUIZMASTER: 'CONNECT_QUIZMASTER',
  WEBSOCKET_ACCEPT_TEAM: 'WEBSOCKET_ACCEPT_TEAM',
  WEBSOCKET_DECLINE_TEAM: 'WEBSOCKET_DECLINE_TEAM',
  WEBSOCKET_START_ROUND: 'START_ROUND',
  NEXT_QUESTION: 'NEXT_QUESTION',
  TEAM_JOINED: 'TEAM_JOINED',
  CLOSE_QUESTION: 'CLOSE_QUESTION',
  UPDATE_SCORE: 'UPDATE_SCORE',
  END_ROUND: 'END_ROUND',
  END_GAME: 'END_GAME'
};

export const GAME_ACTION_TYPES = {
  SET_GAME_STATE: 'SET_GAME_STATE',
  SET_GAME_START_REQUEST_STATE: 'SET_GAME_START_REQUEST_STATE'
};