export const QUESTION_ACTION_TYPES = {
  FETCH_QUESTIONS: 'FETCH_QUESTIONS'
};

export const CATEGORY_ACTION_TYPES = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES'
};

export const QUIZNIGHT_ACTION_TYPES = {
  ACCEPT_TEAM: 'ACCEPT_TEAM',
  DECLINE_TEAM: 'DECLINE_TEAM',
  SET_QUIZNIGHT: 'SET_QUIZNIGHT',
  ROUND_QUESTION_RECEIVED: 'ROUND_QUESTION_RECEIVED',
  ANSWER_RECEIVED: 'ANSWER_RECEIVED',
  ANSWER_RESUBMITTED: 'ANSWER_RESUBMITTED',
  CLOSE_QUESTION: 'CLOSE_QUESTION',
  SET_AMOUNT_QUESTIONS_PER_ROUND: 'SET_AMOUNT_QUESTIONS_PER_ROUND',
  EMPTY_CURRENT_QUESTION: 'EMPTY',
  EMPTY_STATE: 'EMPTY_STATE'
};

export const GAME_ACTION_TYPES = {
  SET_GAME_STATE: 'SET_GAME_STATE',
  SET_GAME_START_REQUEST_STATE: 'SET_GAME_START_REQUEST_STATE'
};