const IDLE = 'IDLE';
const WAITING_FOR_APPLICANTS = 'WAITING_FOR_APPLICANTS';
const CREATING_NEW_ROUND = 'CREATING_NEW_ROUND';
const CHECKING_ANSWERS = 'CHECKING_ANSWERS';
const NEW_ROUND_PENDING = 'NEW_ROUND_PENDING';
const WAITING_FOR_NEXT_QUESTION = 'WAITING_FOR_NEXT_QUESTION';
const END = 'END';

export {
   IDLE,
   WAITING_FOR_APPLICANTS,
   CREATING_NEW_ROUND,
   CHECKING_ANSWERS,
   NEW_ROUND_PENDING,
   WAITING_FOR_NEXT_QUESTION,
   END
};