const MESSAGE_TYPES = {
  ACCEPT_TEAM: 'ACCEPT_TEAM',
  ANSWER_REVIEWED: 'ANSWER_REVIEWED',
  ANSWER_SUBMITTED: 'ANSWER_SUBMITTED',
  CLOSE_QUESTION: 'CLOSE_QUESTION',
  CONNECT_QUIZMASTER: 'CONNECT_QUIZMASTER',
  CONNECT_SCOREBOARD: 'CONNECT_SCOREBOARD',
  CONNECT_TEAM: 'CONNECT_TEAM',
  END_GAME: 'END_GAME',
  END_ROUND: 'END_ROUND',
  NEXT_QUESTION: 'NEXT_QUESTION',
  NEW_QUESTION: 'NEW_QUESTION',
  PENDING: 'PENDING',
  QUESTION_CLOSED: 'QUESTION_CLOSED',
  RE_SUBMIT_ANSWER: 'RE_SUBMIT_ANSWER',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  START_ROUND: 'START_ROUND',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  TEAM_JOINED: 'TEAM_JOINED',
  UPDATE_SCORE: 'UPDATE_SCORE'
}

export default MESSAGE_TYPES;