const MESSAGE_TYPES = {
  ACCEPT_TEAM: 'ACCEPT_TEAM',
  CONNECT_QUIZMASTER: 'CONNECT_QUIZMASTER',
  CONNECT_TEAM: 'CONNECT_TEAM',
  PENDING: 'PENDING',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR'
}

export default MESSAGE_TYPES;