export const NEW_QUESTION = 'NEW_QUESTION';
export const CLOSE_QUESTION = 'CLOSE_QUESTION';
export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const ACCEPT_TEAM = 'ACCEPT_TEAM';

export const SESSION_ACTION_TYPES = {
  LOGIN_REQUEST_STATE: 'LOGIN_STATE',
  LOGIN_STATUS_CHANGE: 'LOGIN_STATUS_CHANGE',
  SET_TEAM_NAME: `SET_TEAM_NAME`
};
