export const NEW_QUESTION = 'NEW_QUESTION';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const TEAM_ALLOWED = 'TEAM_ALLOWED';
export const CONNECT_TEAM = 'CONNECT_TEAM';

export const SESSION_ACTION_TYPES = {
  LOGIN_REQUEST_STATE: 'LOGIN_STATE',
  LOGIN_STATUS_CHANGE: 'LOGIN_STATUS_CHANGE',
  SET_TEAM_NAME: `SET_TEAM_NAME`,
  LOGOUT: 'LOGOUT'
};
