export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';

export const SESSION_ACTION_TYPES = {
  LOGIN_REQUEST_STATE: 'LOGIN_STATE',
  LOGIN_STATUS_CHANGE: 'LOGIN_STATUS_CHANGE',
  SET_TEAM_NAME: `SET_TEAM_NAME`
};
